"""Correlation rule registry.

Each rule maps Windows Event Log activity to an intrusion-phases (kill
chain) stage, MITRE ATT&CK techniques, and the compliance control
families they evidence (ISO/IEC 27001 Annex A / NIST CSF / OWASP Top 10
where relevant). Rules are data, formatted consistently with the JSON
registry exports the tool can ingest, so analysts can extend them.

match semantics (in "opts"):
  "Value"          -> exact (case-insensitive string) equality
  "~substring"     -> case-insensitive containment / regex
  "!Value"         -> NOT equal
  ">N" / "<N"      -> numeric comparison (int)
"""
PHASES = [
    "reconnaissance", "initial_access", "execution", "persistence",
    "privilege_escalation", "credential_access", "defense_evasion",
    "lateral_movement", "impact",
]

RULES = [
    {
        "id": "R-001", "name": "New local user account created",
        "severity": 55, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1136.001"]},
        "iso": ["8.15", "8.16", "5.24"], "nist": ["DE.AE", "RS.MA"],
        "matches": [{"channel": "security", "event_id": 4720}],
        "note": "Creating a fresh account is a classic foothold mechanism.",
    },
    {
        "id": "R-002", "name": "Account enabled after suspected compromise",
        "severity": 40, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1098.001"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4722}],
        "note": "Re-enabled dormant account; correlate with logon success.",
    },
    {
        "id": "R-003", "name": "Account added to privileged group",
        "severity": 70, "stage": "privilege_escalation",
        "mitre": {"tactic": "Privilege Escalation", "technique": ["T1098", "T1078"]},
        "iso": ["8.15", "8.2", "5.15"], "nist": ["PR.AC", "DE.AE"],
        "matches": [
            {"channel": "security", "event_id": 4728},
            {"channel": "security", "event_id": 4732},
            {"channel": "security", "event_id": 4756},
        ],
        "note": "Member added to admin/operator group - escalate credential review.",
    },
    {
        "id": "R-004", "name": "Suspicious account lockout burst",
        "severity": 45, "stage": "credential_access",
        "mitre": {"tactic": "Credential Access", "technique": ["T1110"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "security", "event_id": 4740}],
        "note": "Repeated failed logons preceding lockout suggest brute force.",
    },
    {
        "id": "R-005", "name": "Failed logon - brute force pressure",
        "severity": 60, "stage": "credential_access",
        "mitre": {"tactic": "Credential Access", "technique": ["T1110.001"]},
        "iso": ["8.15", "8.16", "8.5"], "nist": ["DE.CM", "PR.AC"],
        "matches": [{"channel": "security", "event_id": 4625}],
        "note": "Cluster identical source IPs for password-spray detection.",
    },
    {
        "id": "R-006", "name": "Remote interactive logon (RDP)",
        "severity": 62, "stage": "lateral_movement",
        "mitre": {"tactic": "Lateral Movement", "technique": ["T1021.001"]},
        "iso": ["8.15", "8.16", "5.15"], "nist": ["DE.AE", "PR.AC"],
        "matches": [
            {"channel": "security", "event_id": 4624, "opts": {"LogonType": "10"}},
            {"channel": "security", "event_id": 4778},
        ],
        "note": "RDP from non-employee subnet / outside-hours is high priority.",
    },
    {
        "id": "R-007", "name": "Successful logon with elevated privileges",
        "severity": 50, "stage": "privilege_escalation",
        "mitre": {"tactic": "Privilege Escalation", "technique": ["T1078"]},
        "iso": ["8.2", "5.15"], "nist": ["PR.AC", "DE.AE"],
        "matches": [{"channel": "security", "event_id": 4672}],
        "note": "Special privileges assigned; verify 2FA / process justifications.",
    },
    {
        "id": "R-008", "name": "Security log cleared (defense evasion)",
        "severity": 95, "stage": "defense_evasion",
        "mitre": {"tactic": "Defense Evasion", "technique": ["T1070.001"]},
        "iso": ["8.15", "8.16", "8.34"], "nist": ["RS.MA", "DE.CM"],
        "matches": [
            {"channel": "security", "event_id": 1102},
            {"channel": "system", "event_id": 104},
        ],
        "note": "Log clearing almost never legitimate - treat as critical offence.",
    },
    {
        "id": "R-009", "name": "New service installed",
        "severity": 65, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1543.003"]},
        "iso": ["8.15", "8.16", "8.28"], "nist": ["PR.PT", "DE.CM"],
        "matches": [
            {"channel": "system", "event_id": 7045},
            {"channel": "system", "event_id": 4697},
        ],
        "note": "Service pointing to user-writable or temp paths is hostile.",
    },
    {
        "id": "R-010", "name": "Scheduled task created",
        "severity": 60, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1053.005"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [
            {"channel": "security", "event_id": 4698},
            {"channel": "security", "event_id": 4702},
            {"channel": "microsoft-windows-taskscheduler/operational", "event_id": 106},
        ],
        "note": "Inspect TaskName/Action for obfuscated command lines.",
    },
    {
        "id": "R-011", "name": "PowerShell script-block execution",
        "severity": 58, "stage": "execution",
        "mitre": {"tactic": "Execution", "technique": ["T1059.001"]},
        "iso": ["8.15", "8.16", "8.28"], "nist": ["DE.AE", "PR.PT"],
        "matches": [{"channel": "microsoft-windows-powershell/operational", "event_id": 4104}],
        "note": "Correlate script text with IEX, -enc, DownloadString patterns.",
    },
    {
        "id": "R-012", "name": "Process creation - sensitive source area",
        "severity": 55, "stage": "execution",
        "mitre": {"tactic": "Execution", "technique": ["T1059", "T1204.002"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [
            {"channel": "security", "event_id": 4688,
             "opts": {"NewProcessName": "~\\\\Windows\\\\", "CommandLine": "~-enc "}},
            {"channel": "microsoft-windows-sysmon/operational", "event_id": 1,
             "opts": {"CommandLine": "~-enc "}},
        ],
        "note": "Encoded commands issued from system dirs deserve deep review.",
    },
    {
        "id": "R-013", "name": "Credential dumping (LSASS access)",
        "severity": 90, "stage": "credential_access",
        "mitre": {"tactic": "Credential Access", "technique": ["T1003.001"]},
        "iso": ["8.15", "8.16", "8.11"], "nist": ["DE.CM", "RS.MA"],
        "matches": [{"channel": "microsoft-windows-sysmon/operational", "event_id": 10,
                     "opts": {"TargetImage": "~lsass.exe"}}],
        "note": "Process access to lsass = near-certain credential theft.",
    },
    {
        "id": "R-014", "name": "Kerberos service ticket anomaly",
        "severity": 50, "stage": "credential_access",
        "mitre": {"tactic": "Credential Access", "technique": ["T1558"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4769}],
        "note": "Mass service-ticket requests to one SPN suggest Kerberoasting.",
    },
    {
        "id": "R-015", "name": "Network connection to suspicious destination",
        "severity": 55, "stage": "c2",
        "mitre": {"tactic": "Command and Control", "technique": ["T1071"]},
        "iso": ["8.15", "8.16", "8.20"], "nist": ["DE.CM", "PR.PT"],
        "matches": [{"channel": "microsoft-windows-sysmon/operational", "event_id": 3,
                     "opts": {"DestinationIsIpv6": "false"}}],
        "note": "Review against threat-intel and uncommon egress ports.",
    },
    {
        "id": "R-016", "name": "Explicit credential delegation for remote work",
        "severity": 48, "stage": "lateral_movement",
        "mitre": {"tactic": "Lateral Movement", "technique": ["T1078"]},
        "iso": ["8.15", "5.15"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4648}],
        "note": "RunAs to another host - privilege/credential reuse pattern.",
    },
    {
        "id": "R-017", "name": "Potential persistence via registry run-key",
        "severity": 60, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1547.001"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [
            {"channel": "security", "event_id": 4657, "opts": {"ObjectName": "~Run\\"}},
            {"channel": "security", "event_id": 4657, "opts": {"ObjectName": "~RunOnce"}},
        ],
        "note": "Autorun key changed to non-standard binary path.",
    },
    {
        "id": "R-018", "name": "Local account re-enabled / re-created",
        "severity": 35, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1078.003"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [
            {"channel": "security", "event_id": 4738, "opts": {"UserNameChanged": "~"} },
            {"channel": "security", "event_id": 4725},
        ],
        "note": "Deviations in long-lived local accounts; check change history.",
    },
    {
        "id": "R-019", "name": "Windows Defender detected a threat",
        "severity": 85, "stage": "impact",
        "mitre": {"tactic": "Impact", "technique": ["T1485", "T1490"]},
        "iso": ["8.15", "8.16", "8.7"], "nist": ["DE.CM", "RS.MA"],
        "matches": [
            {"channel": "microsoft-windows-windows defender/operational", "event_id": 1116},
            {"channel": "microsoft-windows-windows defender/operational", "event_id": 1117},
        ],
        "note": "Malware sample/action detected - initiate containment.",
    },
    {
        "id": "R-020", "name": "AMSI / script blocking triggered",
        "severity": 75, "stage": "defense_evasion",
        "mitre": {"tactic": "Defense Evasion", "technique": ["T1562.001", "T1059.001"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [
            {"channel": "microsoft-windows-windows defender/operational", "event_id": 1119},
            {"channel": "microsoft-windows-windows defender/operational", "event_id": 1120},
        ],
        "note": "Blocked malware or suspicious script - trace the parent process.",
    },
    {
        "id": "R-021", "name": "WMI / script engines spawning unusual child",
        "severity": 70, "stage": "execution",
        "mitre": {"tactic": "Execution", "technique": ["T1047"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "microsoft-windows-sysmon/operational", "event_id": 1,
                     "opts": {"ParentImage": "~wmic.exe"}}],
        "note": "Windows Management Instrumentation abuse (living-off-the-land).",
    },
    {
        "id": "R-022", "name": "Suspicious SMB share enumeration/access",
        "severity": 45, "stage": "discovery",
        "mitre": {"tactic": "Discovery", "technique": ["T1135"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [
            {"channel": "security", "event_id": 5140},
            {"channel": "security", "event_id": 5145},
        ],
        "note": "Breadth of share paths accessed indicates reconnaissance.",
    },
    {
        "id": "R-023", "name": "Registry persistence primitive modified",
        "severity": 55, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1547.009", "T1112"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "security", "event_id": 4657}],
        "note": "Registry writes by non-admin-process accounts are suspicious.",
    },
    {
        "id": "R-024", "name": "Sensitive object permission changes",
        "severity": 50, "stage": "privilege_escalation",
        "mitre": {"tactic": "Privilege Escalation", "technique": ["T1222"]},
        "iso": ["8.15", "8.16", "5.15"], "nist": ["DE.AE", "PR.AC"],
        "matches": [
            {"channel": "security", "event_id": 4670},
            {"channel": "security", "event_id": 5136},
        ],
        "note": "ACL/DACL change on sensitive objects - audit the grant.",
    },
    {
        "id": "R-025", "name": "Explicit delegation from elevated account",
        "severity": 68, "stage": "lateral_movement",
        "mitre": {"tactic": "Lateral Movement", "technique": ["T1570"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE", "RS.MA"],
        "matches": [{"channel": "security", "event_id": 4624,
                     "opts": {"LogonType": "3", "AccountType": "~User", "ElevatedToken": "%%1843"}}],
        "note": "Network logon with high-il integr token implies lateral pass.",
    },
    {
        "id": "R-026", "name": "Credential validation failures against domain",
        "severity": 42, "stage": "credential_access",
        "mitre": {"tactic": "Credential Access", "technique": ["T1110"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "security", "event_id": 4776, "opts": {"Status": "0xC000006A"}}],
        "note": "Often precedes/parallel to brute force of local accounts.",
    },
    {
        "id": "R-027", "name": "Service start type changed",
        "severity": 52, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1543.003"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "system", "event_id": 7040}],
        "note": "Auto-start persistence - check the updated binary path.",
    },
    {
        "id": "R-028", "name": "PowerShell encoded/obfuscated download",
        "severity": 78, "stage": "execution",
        "mitre": {"tactic": "Execution", "technique": ["T1059.001", "T1105"]},
        "iso": ["8.15", "8.16", "8.20"], "nist": ["DE.AE", "RS.MA"],
        "matches": [{"channel": "microsoft-windows-powershell/operational", "event_id": 4104,
                     "opts": {"ScriptBlockText": "~DownloadString"}}],
        "note": "Script downloading remote payloads - containment advised.",
    },
    {
        "id": "R-029", "name": "Admin logon from non-standard workstation",
        "severity": 60, "stage": "privilege_escalation",
        "mitre": {"tactic": "Initial Access", "technique": ["T1078"], "sub": "admin logon"},
        "iso": ["8.2", "5.15"], "nist": ["PR.AC"],
        "matches": [{"channel": "security", "event_id": 4624, "opts": {"LogonType": "2"}}],
        "note": "Interactive admin login; verify asset + 2FA and time-of-day.",
    },
    {
        "id": "R-030", "name": "Logon type 3 (network) used for admin account",
        "severity": 57, "stage": "lateral_movement",
        "mitre": {"tactic": "Lateral Movement", "technique": ["T1021.002"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4624, "opts": {"LogonType": "3"}}],
        "note": "SMB/net logon - inspect source IP against known server list.",
    },
    {
        "id": "R-031", "name": "New process launched from common 'soft' locations",
        "severity": 64, "stage": "execution",
        "mitre": {"tactic": "Execution", "technique": ["T1204.002", "T1036"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "microsoft-windows-sysmon/operational", "event_id": 1,
                     "opts": {"Image": "~\\\\AppData\\\\"}}],
        "note": "Executables under AppData/Temp - consistent with droppers.",
    },
    {
        "id": "R-032", "name": "File created with executable extension in temp",
        "severity": 62, "stage": "execution",
        "mitre": {"tactic": "Execution", "technique": ["T1204"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "microsoft-windows-sysmon/operational", "event_id": 11,
                     "opts": {"TargetFilename": "~\\.exe\\z"}}],
        "note": "Binary written to temp before execution - replay parent chain.",
    },
    {
        "id": "R-033", "name": "Account enumeration via SMB",
        "severity": 30, "stage": "reconnaissance",
        "mitre": {"tactic": "Reconnaissance", "technique": ["T1087.002"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "security", "event_id": 4776}],
        "note": "Frequent validation calls suggest user enumeration.",
    },
    {
        "id": "R-034", "name": "High count of object access to single target",
        "severity": 20, "stage": "discovery",
        "mitre": {"tactic": "Discovery", "technique": ["T1083"]},
        "iso": ["8.15"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4663}],
        "note": "Burst reads of files - data staging for exfiltration.",
    },
    {
        "id": "R-035", "name": "Windows Filtering Platform blocked connection",
        "severity": 25, "stage": "c2",
        "mitre": {"tactic": "Command and Control", "technique": ["T1071.004"]},
        "iso": ["8.15", "8.20"], "nist": ["PR.PT"],
        "matches": [{"channel": "microsoft-windows-wfp/operational", "event_id": 5157}],
        "note": "Blocked egress - may be C2 detection with failed beacon.",
    },
    {
        "id": "R-036", "name": "Scheduled task content modified",
        "severity": 55, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1053.005"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "security", "event_id": 4702}],
        "note": "Task action changed to script/exe - verify the new action.",
    },
    {
        "id": "R-037", "name": "WMI permanent event subscription (suspected)",
        "severity": 58, "stage": "persistence",
        "mitre": {"tactic": "Persistence", "technique": ["T1546.003"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.CM"],
        "matches": [{"channel": "microsoft-windows-sysmon/operational", "event_id": 12},
                    {"channel": "microsoft-windows-sysmon/operational", "event_id": 13}],
        "note": "Registry events; correlate with WMI consumer creation.",
    },
    {
        "id": "R-038", "name": "Logon process impersonation of SYSTEM",
        "severity": 65, "stage": "privilege_escalation",
        "mitre": {"tactic": "Privilege Escalation", "technique": ["T1134"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4672, "opts": {"SubjectUserName": "~"}}],
        "note": "Compare with expected admin sessions.",
    },
    {
        "id": "R-039", "name": "Domain trust object created",
        "severity": 50, "stage": "lateral_movement",
        "mitre": {"tactic": "Lateral Movement", "technique": ["T1021"]},
        "iso": ["8.15", "8.16"], "nist": ["DE.AE"],
        "matches": [{"channel": "security", "event_id": 4741}],
        "note": "Computer account added - can be abused for machine impersonation.",
    },
    {
        "id": "R-040", "name": "Audit policy modified",
        "severity": 70, "stage": "defense_evasion",
        "mitre": {"tactic": "Defense Evasion", "technique": ["T1562.006"]},
        "iso": ["8.15", "8.34"], "nist": ["DE.CM"],
        "matches": [{"channel": "security", "event_id": 4719}],
        "note": "Disabling audit categories blinds detection - critical TTP.",
    },
]