"""Compliance catalogs for bank-relevant frameworks.

Each control: id, title, category, statement, and `checks` — the types of
evidence this platform can attest (graph analysis, findings scan, audit
trail, data classification). The mapper turns runtime evidence into a live
compliance posture, not a static checklist.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(slots=True)
class Control:
    framework: str
    id: str
    title: str
    category: str
    statement: str
    checks: tuple[str, ...]   # evidence types the mapper understands
    criticality: str = "normal"   # normal | key


OWASP_TOP10_2021: list[Control] = [
    Control("owasp_top10_2021", "A01:2021", "Broken Access Control",
            "Access Control",
            "Deny by default; enforce least privilege; deny access to "
            "Tier-0 except via approved paths.",
            ("tiering", "graph", "rbac"), "key"),
    Control("owasp_top10_2021", "A02:2021", "Cryptographic Failures",
            "Cryptography",
            "Protect data in transit and at rest; strong secrets management.",
            ("crypto", "audit"), "key"),
    Control("owasp_top10_2021", "A03:2021", "Injection",
            "Validation",
            "Validate and sanitize all inputs; parameterized queries only.",
            ("validation",),),
    Control("owasp_top10_2021", "A04:2021", "Insecure Design",
            "Design",
            "Threat-modeled design; tiering model documented and enforced.",
            ("tiering", "validation"),),
    Control("owasp_top10_2021", "A05:2021", "Security Misconfiguration",
            "Hardening",
            "Secure defaults; no debug in prod; hardening baselines (CIS).",
            ("validation", "graph"),),
    Control("owasp_top10_2021", "A06:2021", "Vulnerable/Outdated Components",
            "Patch Mgmt",
            "Inventory and patch vulnerable components; SBOM maintained.",
            ("validation",),),
    Control("owasp_top10_2021", "A07:2021", "Identification & Auth Failures",
            "AuthN",
            "MFA, safe credential storage, anti-brute-force on logon.",
            ("rbac", "audit"), "key"),
    Control("owasp_top10_2021", "A08:2021", "Software & Data Integrity Failures",
            "Integrity", "Verify integrity of deployments and data feeds.",
            ("audit",),),
    Control("owasp_top10_2021", "A09:2021", "Logging & Monitoring Failures",
            "Detection", "Detectable, alerted, retained audit logs.",
            ("audit",), "key"),
    Control("owasp_top10_2021", "A10:2021", "SSRF", "Validation",
            "Outbound request allow-lists; no unvalidated URL fetch.",
            ("validation",),),
]

ISO27001_2022: list[Control] = [
    # Annex A — Technology controls most relevant to an AD attack-path tool
    Control("iso27001_2022", "A.5.15", "Access control", "Organizational",
            "Rules for physical and logical access control.",
            ("rbac", "tiering"), "key"),
    Control("iso27001_2022", "A.5.16", "Identity management",
            "Organizational", "Full lifecycle identity management.",
            ("rbac",),),
    Control("iso27001_2022", "A.5.17", "Authentication information",
            "Organizational", "Secure handling of secrets and credentials.",
            ("crypto",),),
    Control("iso27001_2022", "A.5.18", "Access rights",
            "Organizational", "Provisioning, review, and revocation.",
            ("rbac", "audit"),),
    Control("iso27001_2022", "A.5.23", "Cloud services security",
            "Organizational", "Governance of cloud service usage.",
            ("validation",),),
    Control("iso27001_2022", "A.5.30", "ICT readiness for BC", "Organizational",
            "ICT continuity planning.", ("validation",),),
    Control("iso27001_2022", "A.5.34", "Privacy and PII", "Organizational",
            "Privacy and protection of PII.", ("validation",),),
    Control("iso27001_2022", "A.5.37", "Documented operating procedures",
            "Organizational", "Operating procedures documented.",
            ("audit",),),
    Control("iso27001_2022", "A.8.2", "Privileged access rights",
            "Technological", "Restrict and manage privileged access; "
            "tiered admin model.",
            ("tiering", "graph"), "key"),
    Control("iso27001_2022", "A.8.3", "Information access restriction",
            "Technological", "Restrict access per policy.",
            ("rbac",),),
    Control("iso27001_2022", "A.8.5", "Secure authentication", "Technological",
            "Secure authentication technologies and MFA.",
            ("rbac",), "key"),
    Control("iso27001_2022", "A.8.9", "Configuration management",
            "Technological", "Hardened, documented configurations.",
            ("graph", "validation"),),
    Control("iso27001_2022", "A.8.12", "DLP", "Technological",
            "Data leakage prevention.", ("validation",),),
    Control("iso27001_2022", "A.8.15", "Logging", "Technological",
            "Audit logging with protection against tampering.",
            ("audit",), "key"),
    Control("iso27001_2022", "A.8.16", "Monitoring activities",
            "Technological", "Anomalies and attacks detected.",
            ("audit",),),
    Control("iso27001_2022", "A.8.24", "Use of cryptography", "Technological",
            "Cryptographic controls for confidentiality/integrity.",
            ("crypto",),),
    Control("iso27001_2022", "A.8.25", "Secure development lifecycle",
            "Technological", "Secure coding in the SDLC.",
            ("validation",),),
    Control("iso27001_2022", "A.8.28", "Secure coding", "Technological",
            "Security in the coding process.", ("validation",),),
    Control("iso27001_2022", "A.8.29", "Security testing", "Technological",
            "Security testing in development.", ("validation",),),
    Control("iso27001_2022", "A.8.32", "Change management", "Technological",
            "Change control for all assets.", ("audit",),),
]

NIST_CSF_20: list[Control] = [
    Control("nist_csf_20", "GV.PO-01", "Cybersecurity policy",
            "Govern (GV)", "Policy established, communicated, enforced.",
            ("audit",), "key"),
    Control("nist_csf_20", "GV.RM-01", "Risk management objectives",
            "Govern (GV)", "Risk objectives and appetite documented.",
            ("audit",),),
    Control("nist_csf_20", "ID.AM-01", "Asset inventory", "Identify (ID)",
            "Hardware/software inventory maintained.", ("graph",),),
    Control("nist_csf_20", "ID.AM-02", "Software/service inventory",
            "Identify (ID)", "Inventory of systems and services.",
            ("graph",),),
    Control("nist_csf_20", "ID.AM-05", "Network diagrams", "Identify (ID)",
            "Communication and data flows documented.", ("graph",),),
    Control("nist_csf_20", "PR.AA-01", "Authenticate users", "Protect (PR)",
            "Identity credentials protected; strong auth.",
            ("rbac",), "key"),
    Control("nist_csf_20", "PR.AA-03", "Remote access", "Protect (PR)",
            "Integrity and security of remote access.", ("rbac",),),
    Control("nist_csf_20", "PR.AA-05", "Least privilege", "Protect (PR)",
            "Least privilege and separation of duties.",
            ("tiering", "graph"), "key"),
    Control("nist_csf_20", "PR.PS-01", "Configuration mgmt", "Protect (PR)",
            "Secure configurations established.", ("graph",),),
    Control("nist_csf_20", "PR.IR-01", "Networks protected", "Protect (PR)",
            "Protective posture for networks.", ("validation",),),
    Control("nist_csf_20", "DE.CM-01", "Systems monitored", "Detect (DE)",
            "Devices and systems monitored for adverse events.",
            ("audit",),),
    Control("nist_csf_20", "DE.CM-03", "Personnel activity", "Detect (DE)",
            "Personnel activity monitored.", ("audit",),),
    Control("nist_csf_20", "DE.AE-02", "Events analyzed", "Detect (DE)",
            "Potential adverse events analyzed.", ("audit",),),
    Control("nist_csf_20", "RS.MA-01", "Incident plan executed",
            "Respond (RS)", "Incident response plans executed/tested.",
            ("audit",),),
    Control("nist_csf_20", "RC.RP-01", "Recovery executed", "Recover (RC)",
            "Recovery plans executed/tested.", ("audit",),),
]

NIST_80053_R5: list[Control] = [
    Control("nist_80053_r5", "AC-2", "Account Management", "Access Control",
            "Account types, usage, and risk addressed.", ("rbac", "audit"),
            "key"),
    Control("nist_80053_r5", "AC-3", "Access Enforcement", "Access Control",
            "Approved authorizations enforced.", ("rbac", "graph"), "key"),
    Control("nist_80053_r5", "AC-6", "Least Privilege", "Access Control",
            "Least privilege and authorized access only.",
            ("tiering", "graph"), "key"),
    Control("nist_80053_r5", "AC-6(1)", "Privileged Access", "Access Control",
            "Privileged accounts inventoried and monitored.",
            ("tiering",),),
    Control("nist_80053_r5", "AU-2", "Audit Events", "Audit & Accountability",
            "Events auditable per policy.", ("audit",),),
    Control("nist_80053_r5", "AU-3", "Content of Audit Records", "Audit",
            "Sufficient record content for triage.", ("audit",),),
    Control("nist_80053_r5", "AU-6", "Audit Review/Analysis", "Audit",
            "Audit records reviewed for findings.", ("audit",),),
    Control("nist_80053_r5", "AU-9", "Audit Info Protection", "Audit",
            "Audit info protected from tampering.", ("audit",), "key"),
    Control("nist_80053_r5", "IA-2", "Identification & Authentication",
            "IA", "Users uniquely identified and authenticated.",
            ("rbac",), "key"),
    Control("nist_80053_r5", "IA-5", "Authenticator Management", "IA",
            "Authenticators managed per policy.", ("crypto",), "key"),
    Control("nist_80053_r5", "CM-2", "Baseline Configuration", "CM",
            "Maintained baselines.", ("graph",),),
    Control("nist_80053_r5", "CM-6", "Configuration Settings", "CM",
            "Least-restrictive, documented settings.", ("graph",),),
    Control("nist_80053_r5", "CM-7", "Least Functionality", "CM",
            "Only necessary functions enabled.", ("validation",),),
    Control("nist_80053_r5", "SI-2", "Flaw Remediation", "SI",
            "Vulnerabilities corrected timely.", ("validation",),),
    Control("nist_80053_r5", "SI-4", "System Monitoring", "SI",
            "System monitoring for attacks.", ("audit",),),
]

PCI_DSS_40: list[Control] = [
    Control("pci_dss_40", "1.5.1", "Network security controls", "Network",
            "Inbound/outbound traffic restricted to approved.",
            ("validation",),),
    Control("pci_dss_40", "2.2.4", "Insecure services", "System Hardening",
            "Only necessary services/protocols allowed.", ("graph",),),
    Control("pci_dss_40", "2.2.7", "Non-console admin access", "Hardening",
            "Encrypt all non-console admin access.", ("crypto",),),
    Control("pci_dss_40", "3.4.x", "PAN protection", "Data Protection",
            "Cardholder data unreadable anywhere stored.",
            ("crypto", "validation"), "key"),
    Control("pci_dss_40", "4.2.1", "Strong cryptography in transit",
            "Transmission", "PAN unreadable during transmission.",
            ("crypto",), "key"),
    Control("pci_dss_40", "5.2.x", "Malware defenses", "Malware",
            "Malware mechanisms deployed/running.", ("validation",),),
    Control("pci_dss_40", "6.2.4", "Secure coding", "AppSec",
            "Public-key certs, input validation, crypto controls.",
            ("validation",),),
    Control("pci_dss_40", "6.4.2", "Payment page auth", "AppSec",
            "Unique creds and secrets per person/system.",
            ("rbac",),),
    Control("pci_dss_40", "7.2.1", "Access need-to-know", "Access",
            "Access limited by need-to-know.", ("rbac",), "key"),
    Control("pci_dss_40", "7.2.4", "Least privilege review", "Access",
            "All accounts/apps reviewed and attested.",
            ("tiering", "graph"), "key"),
    Control("pci_dss_40", "7.2.5", "Access reviews", "Access",
            "All user accounts periodic review.", ("audit",),),
    Control("pci_dss_40", "8.2.2", "Group/shared/generic accounts",
            "Identity", "Generic accounts managed or removed.",
            ("rbac",), "key"),
    Control("pci_dss_40", "8.2.4", "MFA for all access into CDE",
            "Identity", "MFA for all access into the CDE.",
            ("rbac",), "key"),
    Control("pci_dss_40", "8.3.x", "Password requirements", "Identity",
            "Minimum 12 chars or 8 + MFA; block common passwords.",
            ("crypto",), "key"),
    Control("pci_dss_40", "8.6.x", "System/service account passwords",
            "Identity",
            "Passwords for system accounts changed periodically, "
            "randomly generated, and documented.",
            ("crypto",), "key"),
    Control("pci_dss_40", "10.2.1", "Event logs", "Logging",
            "All access to data captured.", ("audit",), "key"),
    Control("pci_dss_40", "10.3.x", "Log protection", "Logging",
            "Logs protected 12 months (3 online).", ("audit",), "key"),
    Control("pci_dss_40", "10.4.x", "Log reviews", "Logging",
            "Daily log review for all system components.", ("audit",),),
    Control("pci_dss_40", "11.3.x", "Penetration testing", "Testing",
            "Internal/external pen tests.", ("validation",),),
    Control("pci_dss_40", "11.5.x", "Intrusion detection", "Testing",
            "Change/tamper detection.", ("audit",),),
    Control("pci_dss_40", "12.3.x", "Targeted risk analysis", "Governance",
            "TRA for requirements with defined frequency.", ("audit",),),
    Control("pci_dss_40", "12.5.2", "Scoping assessment", "Governance",
            "IT infrastructure scoping documented.", ("audit",),),
]

CIS_CONTROLS_V8: list[Control] = [
    Control("cis_controls_v8", "1", "Enterprise Assets Inventory", "IG1",
            "Inventory of authorized enterprise assets.", ("graph",), "key"),
    Control("cis_controls_v8", "2", "Software Assets Inventory", "IG1",
            "Inventory of authorized software.", ("validation",),),
    Control("cis_controls_v8", "3", "Data Protection", "IG1",
            "Data handling per classification.", ("validation",), "key"),
    Control("cis_controls_v8", "4", "Secure Configuration", "IG1",
            "Hardened configurations for all assets.", ("graph",),),
    Control("cis_controls_v8", "5", "Account Management", "IG1",
            "Account lifecycle managed.", ("rbac", "audit"), "key"),
    Control("cis_controls_v8", "6", "Access Control Mgmt", "IG1",
            "Access permissions lifecycle.", ("rbac",), "key"),
    Control("cis_controls_v8", "5.4", "Restrict root/admin", "IG1",
            "Restrict admin to least needed.", ("tiering",), "key"),
    Control("cis_controls_v8", "5.2", "Unique passwords", "IG1",
            "Unique, complex passwords for all users.", ("crypto",),),
    Control("cis_controls_v8", "6.1", "Grant via workflow", "IG1",
            "Access grants via approved workflow.", ("audit",),),
    Control("cis_controls_v8", "6.8", "Limit privileges", "IG1",
            "Privileges collected/locked per policy.", ("tiering",),),
    Control("cis_controls_v8", "8", "Audit Log Management", "IG1",
            "Audit logs collected, retained, protected.", ("audit",), "key"),
    Control("cis_controls_v8", "10", "Malware Defenses", "IG1",
            "Malware defenses in place.", ("validation",),),
    Control("cis_controls_v8", "13", "Network Monitoring", "IG2",
            "Network traffic filtered/monitored.", ("validation",),),
    Control("cis_controls_v8", "14", "Security Awareness", "IG1",
            "Security awareness training.", ("audit",),),
    Control("cis_controls_v8", "15", "Service Provider Mgmt", "IG2",
            "Vendor access managed.", ("audit",),),
    Control("cis_controls_v8", "16", "Application Security", "IG2",
            "Software security lifecycle.", ("validation",),),
    Control("cis_controls_v8", "17", "Incident Response Mgmt", "IG2",
            "IR process established.", ("audit",),),
]

FRAMEWORKS: dict[str, dict] = {
    "owasp_top10_2021": {
        "name": "OWASP Top 10 2021",
        "description": "Open Worldwide Application Security Project — "
                       "the ten most critical application security risks.",
        "controls": OWASP_TOP10_2021,
    },
    "iso27001_2022": {
        "name": "ISO/IEC 27001:2022 Annex A",
        "description": "Information security management system (ISMS) "
                       "controls.",
        "controls": ISO27001_2022,
    },
    "nist_csf_20": {
        "name": "NIST CSF 2.0",
        "description": "Govern/Identify/Protect/Detect/Respond/Recover "
                       "functions for sector-agnostic cyber risk.",
        "controls": NIST_CSF_20,
    },
    "nist_80053_r5": {
        "name": "NIST SP 800-53 Rev.5",
        "description": "US federal control catalog, moderate baseline.",
        "controls": NIST_80053_R5,
    },
    "pci_dss_40": {
        "name": "PCI DSS 4.0",
        "description": "Payment card industry data security standard.",
        "controls": PCI_DSS_40,
    },
    "cis_controls_v8": {
        "name": "CIS Controls v8",
        "description": "Prioritized security actions (IG1-IG3).",
        "controls": CIS_CONTROLS_V8,
    },
}
