"""Stdlib-only PDF reporter (minimal, valid PDF 1.4 with a findings table).

No external dependency (reportlab/pyPdf are not bundled) — the file is built
directly: a Type1 Helvetica font, absolute-positioned text blocks and ruled
table rows, assembled through an xref table just like a hand-written PDF.
"""
from __future__ import annotations

import textwrap
from pathlib import Path
from typing import List

PAGE_W = 612
PAGE_H = 792
MARGIN = 50
TABLE_X0 = MARGIN
TABLE_X1 = PAGE_W - MARGIN

COLS = [("Severity", 52), ("Kind", 72), ("Rule ID", 88), ("Device", 66),
        ("Evidence", 116), ("Remediation", 118)]
COL_X = []
x = TABLE_X0
for name, w in COLS:
    COL_X.append(x)
    x += w
COL_X.append(TABLE_X1)  # right edge

SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def _esc(s: str) -> str:
    return (s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
            .encode("latin-1", "replace").decode("latin-1"))


def _text_op(x, y, size, s) -> str:
    return f"BT /F1 {size} Tf {x:.0f} {y:.0f} Td ({_esc(s)}) Tj ET"


def _line_op(x1, x2, y) -> str:
    return f"{x1:.0f} {y:.0f} m {x2:.0f} {y:.0f} l S"


class _Page:
    def __init__(self):
        self.ops: List[str] = []
        self.y = PAGE_H - 60

    def text(self, x, y, size, s):
        self.ops.append(_text_op(x, y, size, s))

    def line(self, x1, y):
        self.ops.append(_line_op(x1, TABLE_X1, y))


def write_report_pdf(findings: List[dict], path, snap, summary=None) -> Path:
    """Write findings as a tabular PDF. `summary` is the score.aggregate() dict."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    summary = summary or {}
    sorted_findings = sorted(
        findings,
        key=lambda f: (SEV_ORDER.get(f.get("severity", "low"), 9), f.get("kind", "")),
    )

    pages = [_Page()]
    page = pages[0]
    top = page.y

    page.text(MARGIN, top, 16, "Firewall Rule Audit Report")
    page.y = top - 22
    page.text(MARGIN, page.y, 10, f"Snapshot: {snap}")
    page.y -= 14

    device = summary.get("device") or (sorted_findings[0].get("device") if sorted_findings else "unknown")
    score_val = summary.get("score", 0.0)
    counts = {k: summary.get(k, 0) for k in ("critical", "high", "medium", "low")}
    page.text(MARGIN, page.y, 10, f"Device / Firewall IP: {device}")
    page.y -= 14
    page.text(MARGIN, page.y, 10, f"Risk score: {score_val}/100  (lower is better)")
    page.y -= 14
    page.text(MARGIN, page.y, 10,
              "Open findings: "
              + "   ".join(f"{k}={counts[k]}" for k in ("critical", "high", "medium", "low")))
    page.y -= 18

    def _draw_header(p):
        p.line(MARGIN, p.y + 9)
        for i, (name, w) in enumerate(COLS):
            p.text(COL_X[i], p.y, 9, name.upper())
        p.y -= 12
        p.line(MARGIN, p.y + 4)

    _draw_header(page)

    def _new_page():
        nonlocal page
        p = _Page()
        pages.append(p)
        page = p
        _draw_header(page)

    def _rows(f):
        raw = [f.get("severity", ""), f.get("kind", ""), f.get("rule_id", ""),
               f.get("device", ""), f.get("evidence", ""), f.get("remediation", "")]
        wrapped = []
        for i, (name, w) in enumerate(COLS):
            chars = max(8, int(w / 4.6))
            lines = textwrap.wrap(raw[i] or "-", chars) or ["-"]
            wrapped.append(lines)
        return wrapped

    lead = 11
    for f in sorted_findings:
        wrapped = _rows(f)
        max_lines = max(len(r) for r in wrapped)
        row_h = max_lines * lead + 6
        if page.y - row_h < 40:
            _new_page()
        page.line(MARGIN, page.y + 9)
        for i, lines in enumerate(wrapped):
            for j, line in enumerate(lines):
                page.text(COL_X[i], page.y - j * lead, 9, line)
        page.y -= row_h
    page.line(MARGIN, page.y + 2)

    page.y -= 16
    page.text(MARGIN, page.y, 8,
              f"Generated by fw-auditor - {len(sorted_findings)} finding(s) at snapshot {snap}")

    path.write_bytes(_assemble(pages))
    return path


def _assemble(pages: List[_Page]) -> bytes:
    n_pages = len(pages)
    contents = ["\n".join(p.ops) for p in pages]
    # object ids:
    # 1 catalog, 2 pages, 3..(3+n_pages-1) page rows, content streams, then font
    first_content = 3 + n_pages
    font_id = first_content + n_pages
    kids = " ".join(f"{3 + i} 0 R" for i in range(n_pages))
    page_ids = [3 + i for i in range(n_pages)]
    content_ids = [first_content + i for i in range(n_pages)]

    objects = []
    objects.append("<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(f"<< /Type /Pages /Kids [{kids}] /Count {n_pages} >>")
    for pid, cid in zip(page_ids, content_ids):
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W} {PAGE_H}] "
            f"/Resources << /Font << /F1 {font_id} 0 R >> >> /Contents {cid} 0 R >>"
        )
    for content in contents:
        data = content.encode("latin-1")
        objects.append(b"<< /Length %d >>\nstream\n" % len(data) + data + b"\nendstream")
    objects.append(
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"
    )

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out.extend(f"{i} 0 obj\n".encode("latin-1"))
        if isinstance(body, bytes):
            out.extend(body)
        else:
            out.extend(body.encode("latin-1"))
        out.extend(b"\nendobj\n")
    xref_pos = len(out)
    n = len(objects)
    out.extend(f"xref\n0 {n + 1}\n".encode("latin-1"))
    out.extend(b"0000000000 65535 f \n")
    for off in offsets:
        out.extend(f"{off:010d} 00000 n \n".encode("latin-1"))
    out.extend(f"trailer\n<< /Size {n + 1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode("latin-1"))
    return bytes(out)