MITRE_TECHNIQUES = [
    ("T1566", "Phishing", "Initial Access",
     "Adversaries send crafted emails to harvest credentials or deploy payloads.",
     "windows,linux,mac,email"),
    ("T1190", "Exploit Public-Facing Application", "Initial Access",
     "Adversaries exploit a vulnerability in an internet-facing application.",
     "windows,linux,web"),
    ("T1078", "Valid Accounts", "Initial Access",
     "Adversaries leverage legitimate credentials to access resources.",
     "windows,linux,cloud"),
    ("T1059", "Command and Scripting Interpreter", "Execution",
     "Adversaries abuse interpreters such as PowerShell or bash to execute commands.",
     "windows,linux,mac"),
    ("T1204", "User Execution", "Execution",
     "Adversaries rely on user action, such as opening a macro document.",
     "windows,linux,mac"),
    ("T1053", "Scheduled Task/Job", "Execution",
     "Adversaries schedule tasks or jobs for code execution and persistence.",
     "windows,linux,mac"),
    ("T1547", "Boot or Logon Autostart Execution", "Persistence",
     "Adversaries configure autostart locations to execute on logon or boot.",
     "windows,mac"),
    ("T1136", "Create Account", "Persistence",
     "Adversaries create accounts to maintain access to the environment.",
     "windows,linux,cloud"),
    ("T1548", "Abuse Elevation Control Mechanism", "Privilege Escalation",
     "Adversaries bypass or abuse mechanisms like UAC or su/sudo.",
     "windows,linux,mac"),
    ("T1068", "Exploitation for Privilege Escalation", "Privilege Escalation",
     "Adversaries exploit a vulnerability to gain elevated privileges.",
     "windows,linux,mac"),
    ("T1562", "Impair Defenses", "Defense Evasion",
     "Adversaries disable or impair security tools and logging.",
     "windows,linux,mac"),
    ("T1070", "Indicator Removal on Host", "Defense Evasion",
     "Adversaries delete or alter artifacts that indicate malicious activity.",
     "windows,linux,mac"),
    ("T1027", "Obfuscated Files or Information", "Defense Evasion",
     "Adversaries obfuscate payloads to evade detection engines.",
     "windows,linux,mac,cloud"),
    ("T1003", "OS Credential Dumping", "Credential Access",
     "Adversaries dump credentials from operating system memory or stores.",
     "windows,linux,mac"),
    ("T1110", "Brute Force", "Credential Access",
     "Adversaries attempt many credential combinations to gain access.",
     "windows,linux,mac,cloud"),
    ("T1087", "Account Discovery", "Discovery",
     "Adversaries enumerate accounts and permissions in a system.",
     "windows,linux,mac,cloud"),
    ("T1057", "Process Discovery", "Discovery",
     "Adversaries enumerate running processes to understand the environment.",
     "windows,linux,mac"),
    ("T1021", "Remote Services", "Lateral Movement",
     "Adversaries use remote services such as SMB/WinRM/SSH to move laterally.",
     "windows,linux,mac"),
    ("T1550", "Use Alternate Authentication Material", "Lateral Movement",
     "Adversaries reuse stolen hashes, tickets, or tokens to authenticate.",
     "windows,cloud"),
    ("T1071", "Application Layer Protocol", "Command and Control",
     "Adversaries use application protocols like HTTPS/DNS for C2.",
     "windows,linux,mac,network"),
    ("T1105", "Ingress Tool Transfer", "Command and Control",
     "Adversaries copy tools into the compromised environment.",
     "windows,linux,mac"),
    ("T1048", "Exfiltration Over Alternative Protocol", "Exfiltration",
     "Adversaries exfiltrate data over protocols other than the primary C2 channel.",
     "windows,linux,mac,network"),
    ("T1486", "Data Encrypted for Impact", "Impact",
     "Adversaries encrypt data to interrupt availability (ransomware impact).",
     "windows,linux,mac"),
    ("T1489", "Service Stop", "Impact",
     "Adversaries stop or disable services to disrupt availability.",
     "windows,linux,mac"),
    ("T1490", "Inhibit System Recovery", "Impact",
     "Adversaries delete backups and recovery points to block restoration.",
     "windows,linux,mac"),
]

CONTROLS = [
    ("A.5.15", "Access Control", "RBAC with red/blue separation of duties",
     "PR.AC", "A01", "implemented"),
    ("A.8.24", "Use of Cryptography", "AES-256 at rest, TLS 1.3 in transit",
     "PR.DS", "A02", "implemented"),
    ("A.8.28", "Secure Coding", "OWASP-aligned SDLC and dependency scanning",
     "PR.AT", "A03", "implemented"),
    ("A.5.28", "Logging and Monitoring", "Immutable audit trail of all platform actions",
     "DE.CM", "A09", "implemented"),
    ("A.8.12", "Data Leakage Prevention", "Contained sandbox for exfiltration tests",
     "PR.DS", "A05", "partial"),
    ("A.5.34", "Protection of Information Systems", "Hardened OS images and WAF",
     "PR.PT", "A05", "implemented"),
]