r"""CIS Benchmark-style control catalog (Windows 10/11 Enterprise, v3.x alignment).

Static data. IDs follow CIS section numbering where practical; this is a
pragmatic subset (~55 controls) chosen for assessment value on typical SOC
endpoints. Each control names its collector + spec.

audit_spec shapes:
  registry:  {"hive": "HKLM", "path": r"SOFTWARE\...", "value": "Name",
              "expect": [op, expected], "value_type": "int|str|enum", "missing": "fail|pass|na"}
  service:   {"name": "W32Time", "expect": [op, expected]}   # observed: Running|Stopped|NotFound
  command:   {"argv": ["net", "accounts"], "parse": "min_pass_len", "expect": [op, v]}
  auditpol:  {"subcategory": "Credential Validation", "field": "Success|Failure",
              "expect": [op, "Enabled"]}
  defender:  {"pref": "DisableRealtimeMonitoring", "expect": [op, "0"]}
"""

from __future__ import annotations

from cisguard.domain.models import Category, Control, Severity

R = "registry"
S = "service"
C = "command"
A = "auditpol"
D = "defender"

CONTROLS: list[Control] = [
    # ---------------- 1. Account Policies ----------------
    Control("1.1.1", "Password history: 24 or more passwords remembered", Category.ACCOUNT_POLICIES, 1, Severity.MEDIUM,
            "Prevents reuse of recent passwords, limiting impact of credential guessing.",
            "Set 'Enforce password history' to 24+ via Local Security Policy / GPO.",
            C, {"argv": ["net", "accounts"], "parse": "password_hist_len", "expect": ["gte", 24]}),
    Control("1.1.2", "Maximum password age: 365 or fewer days (not 0)", Category.ACCOUNT_POLICIES, 1, Severity.MEDIUM,
            "Limits the lifetime of a stolen password.",
            "Set 'Maximum password age' to 90-365 days; never 0 (never expires).",
            C, {"argv": ["net", "accounts"], "parse": "max_pass_age", "expect": ["lte", 365]}),
    Control("1.1.3", "Minimum password length: 14 or more characters", Category.ACCOUNT_POLICIES, 1, Severity.HIGH,
            "Longer passwords resist offline cracking after hash theft.",
            "Set 'Minimum password length' to 14+.",
            C, {"argv": ["net", "accounts"], "parse": "min_pass_len", "expect": ["gte", 14]}),
    Control("1.1.4", "Password must meet complexity requirements: Enabled", Category.ACCOUNT_POLICIES, 1, Severity.HIGH,
            "Complexity increases keyspace against brute force.",
            "Enable 'Password must meet complexity requirements'.",
            C, {"argv": ["net", "accounts"], "parse": "complexity", "expect": ["eq", "Yes"]}),
    Control("1.1.5", "Store passwords using reversible encryption: Disabled", Category.ACCOUNT_POLICIES, 1, Severity.CRITICAL,
            "Reversible storage effectively plaintext-equivalent credentials.",
            "Disable 'Store passwords using reversible encryption'.",
            C, {"argv": ["net", "accounts"], "parse": "reversible", "expect": ["eq", "No"]}),

    Control("1.2.1", "Account lockout duration: 15 or more minutes", Category.ACCOUNT_POLICIES, 1, Severity.MEDIUM,
            "Lockout slows online brute force.",
            "Set 'Account lockout duration' to 15+ minutes.",
            C, {"argv": ["net", "accounts"], "parse": "lockout_duration", "expect": ["gte", 15]}),
    Control("1.2.2", "Account lockout threshold: 5 or fewer invalid attempts", Category.ACCOUNT_POLICIES, 1, Severity.HIGH,
            "Caps online guessing attempts before lockout.",
            "Set 'Account lockout threshold' to 5 or fewer.",
            C, {"argv": ["net", "accounts"], "parse": "lockout_threshold", "expect": ["lte", 5]}),
    Control("1.2.3", "Reset account lockout counter after: 15+ minutes", Category.ACCOUNT_POLICIES, 1, Severity.LOW,
            "Counter window keeps lockout meaningful.",
            "Set 'Reset account lockout counter after' to 15+ minutes.",
            C, {"argv": ["net", "accounts"], "parse": "lockout_reset", "expect": ["gte", 15]}),

    # ---------------- 2. Local Policies / Audit ----------------
    Control("2.1.1", "Audit Credential Validation: Success and Failure", Category.LOCAL_POLICIES, 1, Severity.CRITICAL,
            "Core evidence for pass-the-hash and brute-force detection.",
            "Advanced Audit Policy: Logon/Logoff → Credential Validation = Success, Failure.",
            A, {"subcategory": "Credential Validation", "expect_success": True, "expect_failure": True}),
    Control("2.1.2", "Audit Logon: Success and Failure", Category.LOCAL_POLICIES, 1, Severity.CRITICAL,
            "Primary logon telemetry for SIEM correlation.",
            "Advanced Audit Policy: Logon/Logoff → Logon = Success, Failure.",
            A, {"subcategory": "Logon", "expect_success": True, "expect_failure": True}),
    Control("2.1.3", "Audit Account Lockout: Failure", Category.LOCAL_POLICIES, 1, Severity.MEDIUM,
            "Lockout events feed brute-force alerting.",
            "Advanced Audit Policy: Logon/Logoff → Account Lockout = Failure.",
            A, {"subcategory": "Account Lockout", "expect_failure": True}),
    Control("2.1.4", "Audit Other Logon/Logoff Events: Success", Category.LOCAL_POLICIES, 1, Severity.LOW,
            "Covers sessions not captured by Logon events.",
            "Advanced Audit Policy: Logon/Logoff → Other Logon/Logoff = Success.",
            A, {"subcategory": "Other Logon/Logoff Events", "expect_success": True}),
    Control("2.2.1", "Audit Process Creation: Success", Category.LOCAL_POLICIES, 1, Severity.CRITICAL,
            "Sysmon/4688 process telemetry foundation for EDR-style hunting.",
            "Advanced Audit Policy: Detailed Tracking → Process Creation = Success.",
            A, {"subcategory": "Process Creation", "expect_success": True}),
    Control("2.2.2", "Audit Registry Event: Success/Failure", Category.LOCAL_POLICIES, 2, Severity.MEDIUM,
            "Detects persistence via Run keys and service registry writes.",
            "Advanced Audit Policy: Detailed Tracking → Registry (process termination off) set per CIS.",
            A, {"subcategory": "Registry", "expect_success": True}),
    Control("2.3.1", "Audit Security Group Management: Success", Category.LOCAL_POLICIES, 1, Severity.MEDIUM,
            "Group membership changes are privilege escalation evidence.",
            "Advanced Audit Policy: Account Management → Security Group Management = Success.",
            A, {"subcategory": "Security Group Management", "expect_success": True}),
    Control("2.3.2", "Audit User Account Management: Success and Failure", Category.LOCAL_POLICIES, 1, Severity.HIGH,
            "Captures account creation, disable, and password changes.",
            "Advanced Audit Policy: Account Management → User Account Management = Success, Failure.",
            A, {"subcategory": "User Account Management", "expect_success": True, "expect_failure": True}),
    Control("2.4.1", "Audit Removable Storage: Success/Failure", Category.LOCAL_POLICIES, 1, Severity.MEDIUM,
            "USB exfiltration visibility.",
            "Advanced Audit Policy: Object Access → Removable Storage = Success, Failure.",
            A, {"subcategory": "Removable Storage", "expect_success": True, "expect_failure": True}),
    Control("2.5.1", "Audit Security State Change: Success", Category.LOCAL_POLICIES, 1, Severity.MEDIUM,
            "Boot/system security changes should be rare and reviewed.",
            "Advanced Audit Policy: System → Security State Change = Success.",
            A, {"subcategory": "Security State Change", "expect_success": True}),
    Control("2.5.2", "Audit Security System Extension: Success", Category.LOCAL_POLICIES, 1, Severity.MEDIUM,
            "New security packages/auth filters are persistence vectors.",
            "Advanced Audit Policy: System → Security System Extension = Success.",
            A, {"subcategory": "Security System Extension", "expect_success": True}),
    Control("2.5.3", "Audit System Integrity: Success and Failure", Category.LOCAL_POLICIES, 1, Severity.HIGH,
            "Integrity events (e.g., Secure Boot violations) are high-signal.",
            "Advanced Audit Policy: System → System Integrity = Success, Failure.",
            A, {"subcategory": "System Integrity", "expect_success": True, "expect_failure": True}),

    # ---------------- 3. Event Log sizes ----------------
    Control("3.1.1", "Application event log size: 32768 KB or more", Category.EVENT_LOG, 1, Severity.LOW,
            "Small logs evict evidence early.",
            "Raise Application log maximum size to ≥32768 KB.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\EventLog\Application", "value": "MaxSize", "expect": ["gte", 32768], "value_type": "int", "missing": "fail"}),
    Control("3.1.2", "Security event log size: 196608 KB or more", Category.EVENT_LOG, 1, Severity.MEDIUM,
            "Security log is primary audit evidence store.",
            "Raise Security log maximum size to ≥196608 KB.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\EventLog\Security", "value": "MaxSize", "expect": ["gte", 196608], "value_type": "int", "missing": "fail"}),
    Control("3.1.3", "System event log size: 32768 KB or more", Category.EVENT_LOG, 1, Severity.LOW,
            "System log retains service/driver evidence.",
            "Raise System log maximum size to ≥32768 KB.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\EventLog\System", "value": "MaxSize", "expect": ["gte", 32768], "value_type": "int", "missing": "fail"}),

    # ---------------- 4. System Services ----------------
    Control("4.1.1", "Print Spooler (Spooler): Disabled or not installed", Category.SYSTEM_SERVICES, 2, Severity.HIGH,
            "PrintNightmare-class RCE surface; unnecessary on non-print servers.",
            "Disable Spooler via services.msc or GPO if printing is not required.",
            S, {"name": "Spooler", "expect": ["in", ["Stopped", "NotFound"]]}),
    Control("4.1.2", "Windows Remote Registry (RemoteRegistry): Disabled", Category.SYSTEM_SERVICES, 2, Severity.HIGH,
            "Remote registry access enables remote enumeration/tampering.",
            "Disable RemoteRegistry.",
            S, {"name": "RemoteRegistry", "expect": ["eq", "Disabled"]}),
    Control("4.1.3", "SSDP Discovery (SSDPSRV): Disabled", Category.SYSTEM_SERVICES, 2, Severity.MEDIUM,
            "UPnP discovery exposes network info and enables SSRF-style pivots.",
            "Disable SSDPSRV.",
            S, {"name": "SSDPSRV", "expect": ["eq", "Disabled"]}),
    Control("4.1.4", "UPnP Device Host (upnphost): Disabled", Category.SYSTEM_SERVICES, 2, Severity.MEDIUM,
            "Companion to SSDP; removes UPnP host surface.",
            "Disable upnphost.",
            S, {"name": "upnphost", "expect": ["eq", "Disabled"]}),
    Control("4.1.5", "Fax (Fax): Disabled or not installed", Category.SYSTEM_SERVICES, 1, Severity.LOW,
            "Legacy service, rarely required.",
            "Disable Fax if present.",
            S, {"name": "Fax", "expect": ["in", ["Disabled", "NotFound"]]}),
    Control("4.2.1", "Windows Time (W32Time): Running or Manual", Category.SYSTEM_SERVICES, 1, Severity.LOW,
            "Time sync underpins Kerberos and log correlation.",
            "Ensure W32Time is not Disabled.",
            S, {"name": "W32Time", "expect": ["not_in", ["Disabled"]]}),
    Control("4.2.2", "Windows Defender Firewall (MpsSvc): Running", Category.SYSTEM_SERVICES, 1, Severity.CRITICAL,
            "Host firewall is a primary containment control.",
            "Ensure Windows Firewall service is Running.",
            S, {"name": "MpsSvc", "expect": ["eq", "Running"]}),

    # ---------------- 5. Registry hardening ----------------
    Control("5.1.1", "LM hash storage disabled (NoLMHash)", Category.REGISTRY, 1, Severity.CRITICAL,
            "LM hashes are trivially crackable legacy credentials.",
            r"Set HKLM\SYSTEM\CurrentControlSet\Control\Lsa : NoLMHash = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa", "value": "NoLMHash", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.1.2", "Restrict anonymous enumeration of SAM accounts", Category.REGISTRY, 1, Severity.HIGH,
            "Blocks unauthenticated account enumeration.",
            r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa : RestrictAnonymousSAM = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa", "value": "RestrictAnonymousSAM", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.1.3", "Restrict anonymous enumeration of SAM accounts and shares", Category.REGISTRY, 1, Severity.HIGH,
            "Blocks anonymous share/account listing.",
            r"HKLM\SYSTEM\...\Lsa : RestrictAnonymous = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa", "value": "RestrictAnonymous", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.1.4", "NTLMv2 / LM compatibility level = 5 (NTLMv2 only)", Category.REGISTRY, 1, Severity.HIGH,
            "Forces strongest NTLM protocol; defeats LM/NTLMv1 downgrade.",
            r"HKLM\SYSTEM\...\Lsa : LmCompatibilityLevel = 5.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa", "value": "LmCompatibilityLevel", "expect": ["eq", 5], "value_type": "int", "missing": "fail"}),
    Control("5.1.5", "AllowMicrosoftAccounts: block blank/local passwords", Category.REGISTRY, 1, Severity.LOW,
            "Prevents Microsoft-account-linked blank-password bypass.",
            r"HKLM\SYSTEM\...\Lsa : LimitBlankPasswordUse = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa", "value": "LimitBlankPasswordUse", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.2.1", "Force SMB signing (RequireSecuritySignature)", Category.REGISTRY, 1, Severity.HIGH,
            "SMB signing defeats NTLM relay on SMB.",
            r"HKLM\SYSTEM\...\LanmanServer\Parameters : RequireSecuritySignature = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "value": "RequireSecuritySignature", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.2.2", "SMB server encryption enabled", Category.REGISTRY, 2, Severity.MEDIUM,
            "Encrypts SMB3 traffic end-to-end.",
            r"HKLM\SYSTEM\...\LanmanServer\Parameters : EncryptData = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "value": "EncryptData", "expect": ["eq", 1], "value_type": "int", "missing": "na"}),
    Control("5.2.3", "Disable SMB v1 server", Category.REGISTRY, 1, Severity.CRITICAL,
            "SMBv1 is exploited by EternalBlue-family tooling.",
            r"HKLM\SYSTEM\...\LanmanServer\Parameters : SMB1 = 0 (or remove feature).",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "value": "SMB1", "expect": ["eq", 0], "value_type": "int", "missing": "pass"}),
    Control("5.2.4", "Disable SMB v1 client (HfsDisableSMB1)", Category.REGISTRY, 1, Severity.CRITICAL,
            "Client-side SMBv1 enables share-borne worm pivots.",
            r"HKLM\SYSTEM\...\LanmanWorkstation : AllowInsecureGuestAuth = 0 and FS SMB1 disabled.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters", "value": "AllowInsecureGuestAuth", "expect": ["eq", 0], "value_type": "int", "missing": "pass"}),
    Control("5.3.1", "UAC: Admin Approval Mode for built-in Administrator", Category.REGISTRY, 1, Severity.HIGH,
            "Forces consent prompt for the RID-500 account.",
            r"HKLM\...\Policies\System : FilterAdministratorToken = 1.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "value": "FilterAdministratorToken", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.3.2", "UAC: Admin Approval Mode for all admins", Category.REGISTRY, 1, Severity.HIGH,
            "Core UAC protection for all administrator tokens.",
            r"HKLM\...\Policies\System : EnableLUA = 1.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "value": "EnableLUA", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.3.3", "UAC: prompt for credentials on secure desktop", Category.REGISTRY, 1, Severity.MEDIUM,
            "Secure desktop mitigates shimming/spoofing of UAC prompts.",
            r"HKLM\...\Policies\System : PromptOnSecureDesktop = 1.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "value": "PromptOnSecureDesktop", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("5.3.4", "UAC: elevation prompt for admins = secure desktop", Category.REGISTRY, 1, Severity.MEDIUM,
            "Ensures consent happens on the secure desktop.",
            r"HKLM\...\Policies\System : ConsentPromptBehaviorAdmin = 2.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "value": "ConsentPromptBehaviorAdmin", "expect": ["eq", 2], "value_type": "int", "missing": "fail"}),
    Control("5.4.1", "Disable autorun/autoplay on all drives", Category.REGISTRY, 1, Severity.HIGH,
            "Blocks USB-borne execution via autorun.inf.",
            r"HKLM\...\Policies\Explorer : NoDriveTypeAutoRun = 255 (0xFF).",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "value": "NoDriveTypeAutoRun", "expect": ["eq", 255], "value_type": "int", "missing": "fail"}),
    Control("5.4.2", "Disable autocomplete in Win+R / Explorer", Category.REGISTRY, 2, Severity.LOW,
            "Reduces leakage of sensitive paths in shared sessions.",
            r"HKLM\...\Policies\System : EnableAutoComplete = 0 (as applicable).",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "value": "EnableAutoComplete", "expect": ["eq", 0], "value_type": "int", "missing": "pass"}),
    Control("5.5.1", "BitLocker device encryption: protection on (C:)", Category.REGISTRY, 1, Severity.HIGH,
            "Full-disk encryption protects data at rest from offline attack.",
            "Enable BitLocker on OS volume (assessed via manage-bde).",
            C, {"argv": ["manage-bde", "-status", "C:"], "parse": "bitlocker_protection", "expect": ["eq", "On"]}),
    Control("5.6.1", "Remote Desktop: NLA required", Category.REGISTRY, 1, Severity.CRITICAL,
            "NLA prevents pre-auth RDP exposure to credential attacks.",
            r"HKLM\...\Terminal Server : UserAuthentication = 1.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp", "value": "UserAuthentication", "expect": ["eq", 1], "value_type": "int", "missing": "na"}),
    Control("5.6.2", "Remote Desktop: disabled unless required", Category.REGISTRY, 1, Severity.MEDIUM,
            "RDP is a top ransomware entry vector.",
            "Disable RDP (fDenyTSConnections = 1) if not required.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Terminal Server", "value": "fDenyTSConnections", "expect": ["eq", 1], "value_type": "int", "missing": "pass"}),

    # ---------------- 6. Defender / additional ----------------
    Control("6.1.1", "Defender real-time protection enabled", Category.DEFENSE, 1, Severity.CRITICAL,
            "Primary on-access malware control.",
            "Ensure DisableRealtimeMonitoring = 0.",
            D, {"pref": "DisableRealtimeMonitoring", "expect": ["eq", "0"]}),
    Control("6.1.2", "Defender behavior monitoring enabled", Category.DEFENSE, 1, Severity.HIGH,
            "Catches scripted/fileless behaviors.",
            "Ensure DisableBehaviorMonitoring = 0.",
            D, {"pref": "DisableBehaviorMonitoring", "expect": ["eq", "0"]}),
    Control("6.1.3", "Defender script scanning enabled", Category.DEFENSE, 1, Severity.HIGH,
            "Inspects PowerShell/VBScript/JScript at runtime.",
            "Ensure DisableScriptScanning = 0.",
            D, {"pref": "DisableScriptScanning", "expect": ["eq", "0"]}),
    Control("6.1.4", "Defender cloud-delivered protection enabled", Category.DEFENSE, 1, Severity.MEDIUM,
            "Cloud verdicts block fast-moving threats (assess org policy for data flow).",
            "Ensure MAPS reporting is enabled (1 or 2).",
            D, {"pref": "MAPSReporting", "expect": ["in", ["1", "2"]]}),
    Control("6.1.5", "Defender potentially-unwanted-app (PUA) blocking", Category.DEFENSE, 1, Severity.MEDIUM,
            "Blocks adware/miner-class unwanted software.",
            "Ensure PUAProtection = 1.",
            D, {"pref": "PUAProtection", "expect": ["eq", "1"]}),
    Control("6.2.1", "PowerShell script-block logging enabled", Category.DEFENSE, 1, Severity.HIGH,
            "Logs deobfuscated script content — key detection source.",
            r"HKLM\...\PowerShellScriptBlockLogging : EnableScriptBlockLogging = 1.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging", "value": "EnableScriptBlockLogging", "expect": ["eq", 1], "value_type": "int", "missing": "fail"}),
    Control("6.2.2", "PowerShell module logging enabled", Category.DEFENSE, 1, Severity.MEDIUM,
            "Module pipeline execution telemetry.",
            r"HKLM\...\PowerShellModuleLogging : EnableModuleLogging = 1.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging", "value": "EnableModuleLogging", "expect": ["eq", 1], "value_type": "int", "missing": "na"}),
    Control("6.2.3", "PowerShell v2 engine removed", Category.DEFENSE, 1, Severity.HIGH,
            "PSv2 bypasses modern logging/AMSI.",
            r"HKLM\...\PowerShellCore \\ disable v2 via optional feature (proxy: RemoveWindowsPowerShellV2).",
            C, {"argv": ["powershell", "-NoProfile", "-Command",
                        "(Get-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2 -ErrorAction SilentlyContinue).State"],
                "parse": "psv2_state", "expect": ["eq", "Disabled"]}),
    Control("6.3.1", "LLMNR disabled (EnableMulticast=0)", Category.DEFENSE, 1, Severity.HIGH,
            "LLMNR poisoning enables Responder-style credential theft.",
            r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient : EnableMulticast = 0.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient", "value": "EnableMulticast", "expect": ["eq", 0], "value_type": "int", "missing": "fail"}),
    Control("6.3.2", "NetBIOS over TCP/IP disabled on adapters (proxy)", Category.DEFENSE, 1, Severity.MEDIUM,
            "NetBIOS name service poisoning pairs with LLMNR attacks.",
            "Assessed via registry proxy on current adapter bindings.",
            R, {"hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\NetBT\Parameters", "value": "EnableNetbiosOptions", "expect": ["eq", 2], "value_type": "int", "missing": "na"}),
    Control("6.4.1", "Screensaver password required", Category.DEFENSE, 1, Severity.LOW,
            "Physical-presence control for unattended workstations.",
            r"HKLM\...\Policies\Control Panel\Desktop : ScreenSaverIsSecure = 1.",
            R, {"hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "value": "ScreenSaverIsSecure", "expect": ["eq", 1], "value_type": "int", "missing": "na"}),
    Control("6.4.2", "Connected standby / network unlock not permitting bypass (info)", Category.DEFENSE, 2, Severity.INFO,
            "Informational context for BitLocker network unlock exposure.",
            "Review BitLocker network unlock certificates and scope.",
            C, {"argv": ["cmd", "/c", "ver"], "parse": "verbatim", "expect": ["regex", ".+"], "advisory": True}),
]

CONTROLS_BY_ID: dict[str, Control] = {c.control_id: c for c in CONTROLS}

CATEGORIES: list[Category] = [
    Category.ACCOUNT_POLICIES,
    Category.LOCAL_POLICIES,
    Category.EVENT_LOG,
    Category.SYSTEM_SERVICES,
    Category.REGISTRY,
    Category.DEFENSE,
]
