/**
 * Format renderers.
 *
 * All five writers consume the same `ReportModel`, so every format carries
 * identical figures. Shared concerns handled here:
 *
 *   CSV  - RFC 4180 quoting, BOM for Excel, formula-injection neutralisation.
 *   XLSX - styled workbook, frozen headers, autofilter, print setup, metadata.
 *   HTML - self-contained, offline-capable, strict CSP, fully escaped output.
 *   PDF  - vector text (selectable/searchable), paginated tables, embedded PNG.
 *   JSON - the raw model, for machine consumption and diffing.
 *
 * Injection defences (OWASP A03:2021):
 *   - Every cell that originates from user input is HTML-escaped before it can
 *     reach the HTML renderer; no `innerHTML` is ever used server-side.
 *   - Cells beginning with = + - @ TAB CR are prefixed with an apostrophe in
 *     CSV/XLSX so a spreadsheet cannot be coerced into evaluating a formula.
 *   - PDF text is drawn with the text API, never interpreted.
 */

import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { REPORT_FORMATS_MIME, type ReportFormat } from '@prismforge/shared';
import type { ReportModel, ReportSection } from './report.service.js';

export interface RenderedReport {
  body: Buffer;
  mime: string;
  extension: string;
  /** Suggested download filename, without directory components. */
  filename: string;
}

export type ReportRenderer = (model: ReportModel, filenameBase: string) => RenderedReport | Promise<RenderedReport>;

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Neutralises spreadsheet formula injection. */
function neutraliseFormula(value: string): string {
  return /^[=+\-@\t\r]/.test(value) ? `'${value}` : value;
}

function cellText(value: string | number | null): string {
  if (value === null || value === undefined) return '';
  return neutraliseFormula(String(value));
}

export function slug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

export function stamp(model: ReportModel): string {
  return model.meta.generatedAt.replace(/[:.]/g, '-').replace('T', '_').slice(0, 19);
}

function baseName(model: ReportModel): string {
  return `prismforge-${slug(model.meta.subject)}-${stamp(model)}`;
}

/** Escapes the five XML-significant characters. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ---------------------------------------------------------------------------
// JSON
// ---------------------------------------------------------------------------

export const renderJson: ReportRenderer = (model) => {
  const body = Buffer.from(
    JSON.stringify(
      {
        $schema: 'https://prismforge.example/schemas/report-model-1.0.0.json',
        ...model,
      },
      null,
      2,
    ),
    'utf8',
  );
  return {
    body,
    mime: REPORT_FORMATS_MIME.json,
    extension: 'json',
    filename: `${baseName(model)}.json`,
  };
};

// ---------------------------------------------------------------------------
// CSV  (RFC 4180)
// ---------------------------------------------------------------------------

function csvEscape(value: string): string {
  if (/[",\r\n]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
  return value;
}

export const renderCsv: ReportRenderer = (model) => {
  const lines: string[] = [];

  lines.push(csvEscape(`# ${model.meta.title}`));
  lines.push(csvEscape(`# Organisation,${model.meta.organisation}`));
  lines.push(csvEscape(`# Generated at (UTC),${model.meta.generatedAt}`));
  lines.push(csvEscape(`# Generated by,${model.meta.generatedBy.email} (${model.meta.generatedBy.role})`));
  lines.push(csvEscape(`# Correlation id,${model.meta.correlationId}`));
  lines.push(csvEscape(`# Classification,${model.meta.classification}`));
  lines.push(csvEscape(`# Schema version,${model.schemaVersion}`));
  lines.push(csvEscape(`# ${model.meta.provenance}`));
  lines.push('');

  lines.push('SUMMARY');
  lines.push(csvEscape('Field,Value'));
  for (const h of model.headline) lines.push(`${csvEscape(h.label)},${csvEscape(cellText(h.value))}`);
  lines.push('');

  for (const section of model.sections) {
    lines.push(csvEscape(`## ${section.heading}`));
    if (section.note) lines.push(csvEscape(`# ${section.note}`));
    lines.push(section.columns.map((c) => csvEscape(c.label)).join(','));
    for (const row of section.rows) {
      lines.push(section.columns.map((c) => csvEscape(cellText(row[c.key] ?? ''))).join(','));
    }
    lines.push('');
  }

  if (model.notes.length) {
    lines.push(csvEscape('NOTES'));
    for (const n of model.notes) lines.push(csvEscape(`- ${n}`));
    lines.push('');
  }

  // UTF-8 BOM so Excel detects the encoding and renders sRGB hex codes correctly.
  const body = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(lines.join('\r\n'), 'utf8')]);
  return { body, mime: REPORT_FORMATS_MIME.csv, extension: 'csv', filename: `${baseName(model)}.csv` };
};

// ---------------------------------------------------------------------------
// XLSX
// ---------------------------------------------------------------------------

const BRAND_DARK = 'FF1E1B4B';
const BRAND_ACCENT = 'FF7C3AED';
const BRAND_LIGHT = 'FFF5F3FF';

export const renderXlsx: ReportRenderer = async (model) => {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'PrismForge Reporting Engine';
  wb.lastModifiedBy = model.meta.generatedBy.email;
  wb.created = new Date(model.meta.generatedAt);
  wb.modified = new Date();
  wb.title = model.meta.title;
  wb.subject = model.meta.subject;
  wb.description = model.meta.provenance;
  wb.keywords = `ISO27001,NIST,OWASP,audit,${model.meta.classification}`;
  wb.company = model.meta.organisation;
  wb.category = 'Compliance reporting';

  // ---- Cover sheet -----------------------------------------------------
  const cover = wb.addWorksheet('Report', {
    views: [{ showGridLines: false }],
    pageSetup: { orientation: 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
  });

  cover.columns = [{ width: 34 }, { width: 84 }];
  cover.mergeCells('A1:B2');
  const titleCell = cover.getCell('A1');
  titleCell.value = model.meta.title;
  titleCell.font = { size: 18, bold: true, color: { argb: 'FFFFFFFF' } };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_DARK } };
  titleCell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 };
  cover.getRow(1).height = 30;
  cover.getRow(2).height = 12;

  const metaRows: Array<[string, string]> = [
    ['Organisation', model.meta.organisation],
    ['Classification', model.meta.classification],
    ['Generated at (UTC)', model.meta.generatedAt],
    ['Generated by', `${model.meta.generatedBy.email} (${model.meta.generatedBy.role})`],
    ['Correlation id', model.meta.correlationId],
    ['Schema version', model.schemaVersion],
    ['Retention until', model.meta.retentionUntil],
    ['Provenance', model.meta.provenance],
  ];
  cover.addRow([]);
  metaRows.forEach(([k, v], i) => {
    const row = cover.addRow([k, v]);
    row.getCell(1).font = { bold: true, color: { argb: BRAND_DARK } };
    row.getCell(2).alignment = { wrapText: true, vertical: 'top' };
    if (i % 2 === 1) {
      row.eachCell((c) => {
        c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_LIGHT } };
      });
    }
  });

  cover.addRow([]);
  cover.addRow(['Key figures']).font = { bold: true, size: 13, color: { argb: BRAND_DARK } };
  model.headline.forEach((h) => {
    const row = cover.addRow([h.label, h.value]);
    row.getCell(1).font = { bold: true };
    row.getCell(2).font = { bold: true, color: { argb: BRAND_ACCENT } };
  });

  if (model.chain) {
    cover.addRow([]);
    cover.addRow(['Audit chain integrity']).font = { bold: true, size: 13, color: { argb: BRAND_DARK } };
    cover.addRow(['Verified', model.chain.verified ? 'PASS' : 'FAIL']);
    cover.addRow(['Entries verified', model.chain.entries]);
    cover.addRow(['Chain head hash', model.chain.headHash ?? '-']);
    cover.addRow(['Discrepancies', model.chain.errors.length]);
  }

  if (model.notes.length) {
    cover.addRow([]);
    cover.addRow(['Notes']).font = { bold: true, size: 13, color: { argb: BRAND_DARK } };
    for (const n of model.notes) {
      const row = cover.addRow([n]);
      row.getCell(1).alignment = { wrapText: true, vertical: 'top' };
      cover.mergeCells(`A${row.number}:B${row.number}`);
    }
  }

  // ---- Data sheets -----------------------------------------------------
  model.sections.forEach((section, index) => {
    const sheet = wb.addWorksheet(`${index + 1}. ${section.heading}`.slice(0, 31), {
      views: [{ state: 'frozen', ySplit: 1 }],
      pageSetup: {
        orientation: section.columns.length > 6 ? 'landscape' : 'portrait',
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        margins: { left: 0.4, right: 0.4, top: 0.6, bottom: 0.6, header: 0.3, footer: 0.3 },
      },
    });

    sheet.columns = section.columns.map((c) => ({
      header: c.label,
      key: c.key,
      width: c.width ?? Math.min(Math.max(c.label.length + 6, 14), c.wrap ? 48 : 30),
    }));

    const header = sheet.getRow(1);
    header.height = 24;
    header.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    header.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    header.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_DARK } };
      cell.border = { bottom: { style: 'medium', color: { argb: BRAND_ACCENT } } };
    });

    for (const row of section.rows) {
      const values: Record<string, string | number> = {};
      for (const c of section.columns) {
        const raw = row[c.key];
        values[c.key] = typeof raw === 'number' ? raw : cellText(raw ?? '');
      }
      const added = sheet.addRow(values);
      added.alignment = { vertical: 'top', wrapText: false };
      added.eachCell((cell, col) => {
        const def = section.columns[col - 1];
        cell.alignment = { vertical: 'top', horizontal: def?.align ?? 'left', wrapText: Boolean(def?.wrap) };
        if (typeof cell.value === 'number') cell.numFmt = '#,##0';
      });
    }

    if (section.rows.length > 0) {
      sheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: section.columns.length },
      };
    }

    sheet.headerFooter = {
      oddFooter: `${model.meta.classification} - ${esc(model.meta.title)} - page &P of &N`,
    };
  });

  const buffer = await wb.xlsx.writeBuffer();
  return {
    body: Buffer.from(buffer),
    mime: REPORT_FORMATS_MIME.xlsx,
    extension: 'xlsx',
    filename: `${baseName(model)}.xlsx`,
  };
};

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

export const renderHtml: ReportRenderer = (model) => {
  const sectionHtml = (s: ReportSection): string => {
    const head = s.columns
      .map((c) => `<th scope="col" class="${c.align === 'right' ? 'r' : c.align === 'center' ? 'c' : ''}">${esc(c.label)}</th>`)
      .join('');
    const body = s.rows
      .map(
        (r) =>
          `<tr>${s.columns
            .map((c) => {
              const v = r[c.key];
              return `<td class="${c.align === 'right' ? 'r' : c.align === 'center' ? 'c' : ''}${c.wrap ? ' wrap' : ''}">${esc(v ?? '')}</td>`;
            })
            .join('')}</tr>`,
      )
      .join('\n');
    return `
      <section>
        <h2>${esc(s.heading)}</h2>
        ${s.note ? `<p class="note">${esc(s.note)}</p>` : ''}
        <div class="tablewrap">
        <table>
          <thead><tr>${head}</tr></thead>
          <tbody>${body || `<tr><td colspan="${s.columns.length}" class="empty">No rows in this section.</td></tr>`}</tbody>
        </table>
        </div>
      </section>`;
  };

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'">
<meta name="referrer" content="no-referrer">
<title>${esc(model.meta.title)} - ${esc(model.meta.organisation)}</title>
<style>
  *,*::before,*::after{box-sizing:border-box}
  :root{
    --ink:#1e1b4b; --ink-2:#4c1d95; --accent:#7c3aed; --accent-2:#db2777;
    --line:#e2e8f0; --muted:#64748b; --bg:#f8fafc; --ok:#047857; --bad:#b91c1c;
  }
  html{-webkit-print-color-adjust:exact;print-color-adjust:exact}
  body{margin:0;background:var(--bg);color:#0f172a;
    font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
  .page{max-width:1100px;margin:0 auto;padding:32px 20px 72px}
  header.hero{background:linear-gradient(135deg,var(--ink) 0%,var(--ink-2) 45%,var(--accent) 100%);
    color:#fff;border-radius:18px;padding:28px 30px;box-shadow:0 18px 40px -22px rgba(30,27,75,.85)}
  .eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:11px;opacity:.82;font-weight:600}
  h1{margin:8px 0 6px;font-size:28px;line-height:1.15;letter-spacing:-.01em}
  .sub{margin:0;opacity:.9;font-size:14px}
  .chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}
  .chip{background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.28);
    padding:5px 11px;border-radius:999px;font-size:12px;font-weight:600;letter-spacing:.02em}
  .banner{margin:20px 0;padding:14px 18px;border-radius:12px;font-weight:600;display:flex;gap:10px;align-items:center}
  .banner.ok{background:#ecfdf5;border:1px solid #6ee7b7;color:var(--ok)}
  .banner.bad{background:#fef2f2;border:1px solid #fca5a5;color:var(--bad)}
  .headline{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;margin:22px 0 8px}
  .headline div{background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px 14px}
  .headline dt{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:600}
  .headline dd{margin:4px 0 0;font-size:15px;font-weight:700;color:var(--ink);word-break:break-word}
  .shot{width:100%;max-width:520px;margin:8px auto 0;display:block;border-radius:14px;border:1px solid var(--line);
    background:linear-gradient(160deg,#fff,#eef2ff)}
  section{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px 22px;margin:18px 0}
  h2{margin:0 0 4px;font-size:18px;color:var(--ink);letter-spacing:-.01em}
  p.note{margin:0 0 12px;color:var(--muted);font-size:13px}
  .tablewrap{overflow-x:auto}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{background:linear-gradient(180deg,#f5f3ff,#ede9fe);color:var(--ink);text-align:left;
    padding:9px 10px;border-bottom:2px solid var(--accent);font-size:11px;
    text-transform:uppercase;letter-spacing:.06em;white-space:nowrap;position:sticky;top:0}
  td{padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}
  tbody tr:nth-child(even){background:#fafafa}
  tbody tr:hover{background:#f5f3ff}
  td.wrap{white-space:normal;min-width:180px}
  .r{text-align:right;font-variant-numeric:tabular-nums}
  .c{text-align:center}
  td.empty{text-align:center;color:var(--muted);font-style:italic;padding:18px}
  code{font:12px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;background:#f1f5f9;padding:1px 5px;border-radius:5px}
  ol.notes{margin:0;padding-left:20px}
  ol.notes li{margin:5px 0}
  footer{margin-top:26px;padding:18px 20px;border-radius:12px;background:#fff;border:1px solid var(--line);
    color:var(--muted);font-size:12px;line-height:1.6}
  @media print{
    body{background:#fff}
    .page{max-width:none;padding:0}
    header.hero,section,.headline div,footer{box-shadow:none}
    section{break-inside:avoid;page-break-inside:avoid}
    thead{display:table-header-group}
  }
</style>
</head>
<body>
<div class="page">
  <header class="hero">
    <div class="eyebrow">${esc(model.meta.organisation)}</div>
    <h1>${esc(model.meta.title)}</h1>
    <p class="sub">${esc(model.meta.generatedBy.email)} &middot; ${esc(model.meta.generatedAt)} &middot; schema v${esc(model.schemaVersion)}</p>
    <div class="chips">
      <span class="chip">${esc(model.meta.classification)}</span>
      <span class="chip">${esc(model.meta.subject)}</span>
      <span class="chip">ISO/IEC 27001</span>
      <span class="chip">NIST CSF 2.0</span>
      <span class="chip">OWASP ASVS L2</span>
    </div>
  </header>

  ${
    model.chain
      ? `<div class="banner ${model.chain.verified ? 'ok' : 'bad'}">${model.chain.verified ? '&#10003;' : '&#10007;'} Audit chain ${
          model.chain.verified ? 'integrity verified' : 'INTEGRITY FAILURE DETECTED'
        } &mdash; ${esc(String(model.chain.entries))} entries checked, ${esc(String(model.chain.errors.length))} discrepancies.</div>`
      : ''
  }

  <dl class="headline">
    ${model.headline.map((h) => `<div><dt>${esc(h.label)}</dt><dd>${esc(h.value)}</dd></div>`).join('\n    ')}
  </dl>

  ${model.snapshot ? `<img class="shot" alt="Client-rendered 3D preview of the configured product" src="${esc(model.snapshot)}">` : ''}

  ${model.sections.map(sectionHtml).join('\n')}

  ${
    model.notes.length
      ? `<section><h2>Notes &amp; qualifications</h2><ol class="notes">${model.notes
          .map((n) => `<li>${esc(n)}</li>`)
          .join('')}</ol></section>`
      : ''
  }

  <footer>
    <strong>Provenance.</strong> ${esc(model.meta.provenance)}<br>
    <strong>Retention.</strong> This extract is retained until ${esc(model.meta.retentionUntil)} and is destroyed thereafter by the retention job.<br>
    <strong>Handling.</strong> ${esc(model.meta.classification)} &mdash; distribute only to principals with a documented business need.
  </footer>
</div>
</body>
</html>`;

  return {
    body: Buffer.from(html, 'utf8'),
    mime: REPORT_FORMATS_MIME.html,
    extension: 'html',
    filename: `${baseName(model)}.html`,
  };
};

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------

const INK = '#1e1b4b';
const ACCENT = '#7c3aed';
const MUTED = '#64748b';
const LINE = '#e2e8f0';

export const renderPdf: ReportRenderer = async (model) => {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 54, bottom: 54, left: 46, right: 46 },
    info: {
      Title: model.meta.title,
      Author: model.meta.generatedBy.email,
      Subject: `${model.meta.subject} - ${model.meta.classification}`,
      Keywords: `ISO27001,NIST,OWASP,${model.meta.classification}`,
      Creator: 'PrismForge Reporting Engine',
      CreationDate: new Date(model.meta.generatedAt),
    },
  });

  const chunks: Buffer[] = [];
  const finished = new Promise<Buffer>((resolve, reject) => {
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  const pageWidth = doc.page.width - 92;

  // ---- Cover -----------------------------------------------------------
  doc.rect(0, 0, doc.page.width, 190).fill(INK);
  doc.rect(0, 182, doc.page.width, 8).fill(ACCENT);

  doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
  doc.text(model.meta.organisation.toUpperCase(), 46, 44, { characterSpacing: 1.6 });
  doc.fontSize(23).font('Helvetica-Bold').text(model.meta.title, 46, 62, { width: pageWidth });
  doc.fontSize(9).font('Helvetica').fillColor('#c7d2fe');
  doc.text(`${model.meta.generatedBy.email}  -  ${model.meta.generatedAt}  -  schema v${model.schemaVersion}`, 46, 140);

  // Classification banner
  const bannerText = `CLASSIFICATION: ${model.meta.classification}    |    SUBJECT: ${model.meta.subject}`;
  doc.roundedRect(46, 206, pageWidth, 24, 6).fill('#f5f3ff');
  doc.fillColor(ACCENT).fontSize(8.5).font('Helvetica-Bold');
  doc.text(bannerText, 56, 213, { width: pageWidth - 20 });

  if (model.chain) {
    const y = 242;
    const ok = model.chain.verified;
    doc.roundedRect(46, y, pageWidth, 26, 6).fill(ok ? '#ecfdf5' : '#fef2f2');
    doc.fillColor(ok ? '#047857' : '#b91c1c').fontSize(9.5).font('Helvetica-Bold');
    doc.text(
      ok
        ? `Audit chain integrity: VERIFIED - ${model.chain.entries} entries, ${model.chain.errors.length} discrepancies`
        : `Audit chain integrity: FAILURE - ${model.chain.errors.length} discrepancies detected`,
      56,
      y + 8,
      { width: pageWidth - 20 },
    );
  }

  // ---- Headline grid ---------------------------------------------------
  let y = model.chain ? 284 : 250;
  doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text('KEY FIGURES', 46, y);
  y += 16;

  const cols = 2;
  const colW = (pageWidth - 12) / cols;
  model.headline.forEach((h, i) => {
    const cx = 46 + (i % cols) * (colW + 12);
    const cy = y + Math.floor(i / cols) * 34;
    if (cx + colW > doc.page.width - 46) return;
    doc.roundedRect(cx, cy, colW, 29, 5).fill('#ffffff');
    doc.rect(cx, cy, 3, 29).fill(ACCENT);
    doc.fillColor(MUTED).fontSize(7.5).font('Helvetica-Bold');
    doc.text(h.label.toUpperCase(), cx + 9, cy + 6, { width: colW - 16, characterSpacing: 0.6 });
    doc.fillColor(INK).fontSize(9.5).font('Helvetica');
    doc.text(String(h.value), cx + 9, cy + 16, { width: colW - 16, ellipsis: true, lineBreak: false });
  });
  y += Math.ceil(model.headline.length / cols) * 34 + 10;

  // ---- Snapshot --------------------------------------------------------
  if (model.snapshot) {
    const match = /^data:image\/png;base64,(.+)$/.exec(model.snapshot);
    if (match) {
      const img = Buffer.from(match[1]!, 'base64');
      const maxW = 240;
      const h = 190;
      if (y + h < doc.page.height - 70) {
        try {
          doc.image(img, 46, y, { fit: [maxW, h] });
          doc.fillColor(MUTED).fontSize(7.5).font('Helvetica-Oblique');
          doc.text('Client-rendered 3D preview captured at time of report generation.', 300, y + 6, {
            width: pageWidth - 254,
          });
          doc.fillColor(INK).fontSize(9).font('Helvetica-Bold').text('Configuration summary', 300, y + 24);
          doc.fillColor('#334155').fontSize(8.5).font('Helvetica');
          const specSummary = `${model.headline[0]?.value ?? ''} - ${model.headline[2]?.value ?? ''}`;
          doc.text(specSummary, 300, y + 38, { width: pageWidth - 254 });
          y += h + 14;
        } catch {
          /* a malformed snapshot must never abort the report */
        }
      }
    }
  }

  // ---- Sections --------------------------------------------------------
  for (const section of model.sections) {
    if (y > doc.page.height - 150) {
      doc.addPage();
      y = 56;
    }
    y = drawSection(doc, section, y, pageWidth);
  }

  // ---- Notes & footer --------------------------------------------------
  if (model.notes.length) {
    if (y > doc.page.height - 140) {
      doc.addPage();
      y = 56;
    }
    doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text('NOTES & QUALIFICATIONS', 46, y + 8);
    y += 24;
    doc.font('Helvetica').fontSize(8).fillColor('#334155');
    for (const note of model.notes) {
      const h = doc.heightOfString(note, { width: pageWidth - 14 });
      if (y + h > doc.page.height - 70) {
        doc.addPage();
        y = 56;
      }
      doc.circle(50, y + 4, 1.6).fill(ACCENT);
      doc.text(note, 58, y, { width: pageWidth - 14 });
      y += h + 6;
    }
  }

  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const fy = doc.page.height - 42;
    doc.rect(46, fy, pageWidth, 0.8).fill(LINE);
    doc.fillColor(MUTED).fontSize(7).font('Helvetica');
    doc.text(model.meta.provenance, 46, fy + 6, { width: pageWidth - 70, lineBreak: false, ellipsis: true });
    doc.text(`Page ${i + range.start + 1} of ${range.start + range.count}`, 46, fy + 16, {
      width: pageWidth,
      align: 'right',
    });
  }

  doc.end();
  return {
    body: await finished,
    mime: REPORT_FORMATS_MIME.pdf,
    extension: 'pdf',
    filename: `${baseName(model)}.pdf`,
  };
};

function drawSection(doc: PDFKit.PDFDocument, section: ReportSection, startY: number, pageWidth: number): number {
  let y = startY;

  const header = () => {
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(10.5).text(section.heading, 46, y, { width: pageWidth });
    y += 15;
    if (section.note) {
      doc.fillColor(MUTED).font('Helvetica-Oblique').fontSize(7.5).text(section.note, 46, y, { width: pageWidth });
      y += doc.heightOfString(section.note, { width: pageWidth }) + 4;
    }
    y += 3;
  };

  header();

  const columns = section.columns;
  // Distribute the page width proportionally to declared widths, with a floor.
  const weights = columns.map((c) => c.width ?? Math.max(10, Math.min(34, c.label.length + 8)));
  const totalWeight = weights.reduce((a, b) => a + b, 0);
  const widths = weights.map((w) => Math.max(46, (w / totalWeight) * pageWidth));
  const scale = pageWidth / widths.reduce((a, b) => a + b, 0);
  const finalWidths = widths.map((w) => w * scale);

  // Column header row
  doc.roundedRect(46, y, pageWidth, 16, 3).fill('#f5f3ff');
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(6.8);
  let x = 46;
  columns.forEach((c, i) => {
    doc.text(c.label.toUpperCase(), x + 4, y + 5, {
      width: finalWidths[i]! - 8,
      align: c.align === 'right' ? 'right' : c.align === 'center' ? 'center' : 'left',
      ellipsis: true,
      lineBreak: false,
    });
    x += finalWidths[i]!;
  });
  y += 16;

  const maxRows = 400;
  section.rows.slice(0, maxRows).forEach((row, rowIndex) => {
    const cells = columns.map((c) => String(row[c.key] ?? ''));
    const heights = cells.map((v, i) =>
      doc.heightOfString(v, { width: finalWidths[i]! - 8, ellipsis: true }),
    );
    const rowH = Math.min(Math.max(Math.max(...heights, 0) + 6, 12), 44);

    if (y + rowH > doc.page.height - 60) {
      doc.addPage();
      y = 46;
      header();
    }

    if (rowIndex % 2 === 1) {
      doc.rect(46, y, pageWidth, rowH).fill('#fafafa');
    }

    let cx = 46;
    cells.forEach((v, i) => {
      doc.fillColor('#0f172a').font('Helvetica').fontSize(7.2);
      doc.text(v, cx + 4, y + 4, {
        width: finalWidths[i]! - 8,
        align: columns[i]!.align === 'right' ? 'right' : columns[i]!.align === 'center' ? 'center' : 'left',
        ellipsis: true,
        lineBreak: rowH > 16,
      });
      cx += finalWidths[i]!;
    });
    doc.moveTo(46, y + rowH).lineTo(46 + pageWidth, y + rowH).lineWidth(0.4).strokeColor(LINE).stroke();
    y += rowH;
  });

  if (section.rows.length > maxRows) {
    doc.fillColor(MUTED).font('Helvetica-Oblique').fontSize(7);
    doc.text(`... ${section.rows.length - maxRows} further rows truncated in this rendering. Use the CSV or XLSX export for the complete extract.`, 46, y + 4, { width: pageWidth });
    y += 16;
  }

  return y + 14;
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

export const RENDERERS: Record<ReportFormat, ReportRenderer> = {
  csv: renderCsv,
  xlsx: renderXlsx,
  html: renderHtml,
  pdf: renderPdf,
  json: renderJson,
};

export async function render(model: ReportModel): Promise<RenderedReport> {
  return RENDERERS[model.meta.format](model, baseName(model));
}
