import csv
import html
import json
import os
import time
from datetime import datetime, timezone

from ..compat import workspace as ws


def watermark(operator, session_id, scope="OWN / AUTHORIZED DATA ONLY"):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    return "PasswordGuardian Report | operator: {} | session: {} | {}".format(
        operator, session_id, ts
    )


def build_data(meta, summary, items):
    return {
        "meta": meta,
        "summary": summary,
        "items": items,
    }


def _esc(v):
    return html.escape(str(v if v is not None else ""), quote=True)


def build_html(meta, summary, items):
    wm = watermark(meta["operator"], meta["session_id"])
    rows = []
    for it in items:
        status = "cracked" if it.get("candidate") else ("unresolved" if it.get("resolved") is not False else "pending")
        rows.append(
            "<tr>"
            "<td>{}</td><td><code>{}</code></td><td>{}</td><td>{}</td>"
            "<td>{}</td></tr>".format(
                _esc(it.get("pos", "")),
                _esc(it.get("token", "")),
                _esc(" / ".join(it.get("algos") or [])),
                _esc(it.get("salt") or ""),
                _esc(it.get("candidate") or ""),
            )
        )
    table = "<table><thead><tr><th>#</th><th>Hash</th><th>Algorithm</th><th>Salt</th><th>Found plaintext</th></tr></thead><tbody>{}</tbody></table>".format(
        "".join(rows)
    )
    stat_cells = "".join(
        "<b>{}</b> {}".format(_esc(str(v)), _esc(k)) if not isinstance(v, str) else "<b>{}</b> <i>{}</i>".format(_esc(v), k)
        for k, v in summary.items()
        if k not in ("found_map", "attempted")
    )
    return HTML_TEMPLATE.format(
        watermark=_esc(wm),
        scope=_esc(meta.get("scope", "OWN / AUTHORIZED DATA ONLY")),
        operator=_esc(meta["operator"]),
        summary=stat_cells,
        table=table,
    )


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>PasswordGuardian Report</title>
<style>
body{{font-family:Segoe UI,Arial,sans-serif;margin:2em;color:#222}}
.banner{{background:#1b2a4a;color:#fff;padding:.8em 1em;border-radius:6px;font-weight:600}}
.scope{{color:#ffd34d;font-size:.85em;margin-top:.3em}}
.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.6em;margin:1em 0}}
.stats div{{border:1px solid #d5d5d5;padding:.6em;border-radius:4px}}
table{{border-collapse:collapse;width:100%;margin-top:1em}}
th,td{{border:1px solid #ccc;padding:.4em .6em;font-size:.9em;text-align:left}}
th{{background:#eef2f7}}
code{{background:#f4f4f4;padding:.1em .3em;border-radius:3px}}
</style></head><body>
<div class="banner">{watermark}</div>
<div class="scope">SECURITY CLASSIFICATION: {scope}</div>
<div class="stats">{summary}</div>
{table}
<p><small>Generated by PasswordGuardian. For legitimate, authorized testing of passwords you own only.</small></p>
</body></html>"""


def write_csv(path, items):
    with open(path, "w", newline="", encoding="utf-8-sig") as fh:
        writer = csv.writer(fh)
        writer.writerow(["#", "hash", "algorithms", "salt", "status", "plaintext"])
        for it in items:
            writer.writerow(
                [
                    it.get("pos", ""),
                    it.get("token", ""),
                    " / ".join(it.get("algos") or []),
                    it.get("salt") or "",
                    "cracked" if it.get("candidate") else "unresolved",
                    it.get("candidate") or "",
                ]
            )


def write_json(path, data):
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)


def save_encrypted_bundle(path, data, local_machine=False):
    if not ws.bundle_available():
        raise RuntimeError("encrypted bundles require Windows DPAPI")
    payload = json.dumps(data).encode("utf-8")
    ws.save_bundle(path, payload, local_machine=local_machine)
    return path


def load_encrypted_bundle(path):
    if not ws.bundle_available():
        raise RuntimeError("encrypted bundles require Windows DPAPI")
    raw = ws.load_bundle(path)
    return json.loads(raw.decode("utf-8"))